include: package:lint/analysis_options.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.chopper.dart"
    - lib/generated_plugin_registrant.dart

  errors:
    invalid_annotation_target: ignore
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    must_be_immutable: error