name: football
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  chopper: ^4.0.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_linkify: ^5.0.2
  flutter_riverpod: ^1.0.4
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  logging: ^1.0.2
  lottie: ^1.3.0
  responsive_sizer: ^3.0.8
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  chopper_generator: ^4.0.6
  collection: ^1.16.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5
  http: ^0.13.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lint: ^1.8.2
  mocktail: ^0.3.0
  riverpod: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - .env
